apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    service: udagram-reverseproxy
spec:
  ports:
  - name: "8080"
    port: 80
    targetPort: 8080
  selector:
    service: udagram-reverseproxy