apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-udagram-reverseproxy
  labels:
    service: my-udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: my-udagram-reverseproxy
  template:
    metadata:
      labels:
        service: my-udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: christianoj/udagram-reverseproxy:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always