apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-udagram-api-user
  labels:
    app: my-udagram-api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-udagram-api-user
  template:
    metadata:
      labels:
        app: my-udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: christianoj/udagram-api-user:v1
        ports:
          - containerPort: 80
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: postgres_host
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: postgres_db
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: aws_bucket
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: password
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: aws_region
          - name: AWS_PROFILE
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: aws_profile

